version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    branches:
      ignore:
        - gh-pages
    steps:
      - checkout
      - restore_cache:
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install denpendencies
          command: yarn
      - save_cache:
          key: dependencies-cache-{{ checksum "yarn.lock" }}
          path:
            - ./node_modules
      - run:
          name: Test
          command: yarn test
